
import React, { useState, useRef } from 'react';
import { analyzeVideo } from './services/geminiService';
import { extractFrames, downloadReport } from './utils/helpers';
import { AnalysisResult } from './types';
import SEOCard from './components/SEOCard';

// SVGs for Icons
const YTIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.42a2.78 2.78 0 0 0-1.94 2C1 8.11 1 12 1 12s0 3.89.46 5.58a2.78 2.78 0 0 0 1.94 2c1.72.42 8.6.42 8.6.42s6.88 0 8.6-.42a2.78 2.78 0 0 0 1.94-2C23 15.89 23 12 23 12s0-3.89-.46-5.58z"/><polygon points="9.75 15.02 15.5 12 9.75 8.98 9.75 15.02"/></svg>;
const TikTokIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 12a4 4 0 1 0 4 4V4a5 5 0 0 0 5 5"/></svg>;
const FBIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>;
const UploadIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#00D1FF" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>;

const App: React.FC = () => {
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [videoPreview, setVideoPreview] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('video/')) {
        setError('Please upload a valid video file.');
        return;
      }
      setVideoFile(file);
      setVideoPreview(URL.createObjectURL(file));
      setResult(null);
      setError(null);
    }
  };

  const startAnalysis = async () => {
    if (!videoFile) return;
    setIsAnalyzing(true);
    setError(null);
    try {
      const frames = await extractFrames(videoFile, 12);
      const analysis = await analyzeVideo(frames);
      setResult(analysis);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Analysis failed. Please check your API key and network.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    const report = `
VIDSEO AI - EXPERT VIDEO SEO REPORT
====================================
VISUAL HOOK ANALYSIS:
"${result.visualHook}"

YOUTUBE STRATEGY:
- Title: ${result.youtube.title}
- Description: ${result.youtube.description}
- Tags: ${result.youtube.tags}

TIKTOK STRATEGY:
- Captions:
${result.tiktok.captions.map((c, i) => `  ${i + 1}. ${c}`).join('\n')}
- Hashtags: ${result.tiktok.hashtags.join(', ')}

FACEBOOK STRATEGY:
- Post Caption: ${result.facebook.caption}

PLATFORM POLICY STATUS:
- Status: ${result.policyCheck.status}
- Reasoning: ${result.policyCheck.notes}

Generated by VidSEO AI - Frame-by-Frame Expert
    `.trim();
    downloadReport(report, `VidSEO_Strategy_${Date.now()}.txt`);
  };

  return (
    <div className="min-h-screen pb-20 px-4 md:px-8 max-w-7xl mx-auto">
      {/* Header */}
      <header className="py-10 flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="flex items-center gap-5 group">
          <div className="relative">
            <div className="absolute inset-0 bg-[#00D1FF]/20 blur-xl rounded-full group-hover:bg-[#00D1FF]/40 transition-all duration-500"></div>
            <div className="relative w-16 h-16 rounded-full overflow-hidden border-2 border-[#00D1FF]/50 bg-[#1A1A1A] flex items-center justify-center p-0.5 shadow-2xl">
               <img 
                src="logo.png" 
                alt="VidSEO Logo" 
                className="w-full h-full object-cover rounded-full"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = "https://picsum.photos/seed/vidseo/200/200";
                }}
               />
            </div>
          </div>
          <div>
            <h1 className="text-3xl font-black text-white tracking-tighter flex items-center gap-1">
              VidSEO <span className="text-[#00D1FF] bg-clip-text text-transparent bg-gradient-to-r from-[#00D1FF] to-[#007BFF]">AI</span>
            </h1>
            <p className="text-[10px] text-[#00D1FF]/70 font-bold uppercase tracking-[0.2em] mt-0.5">
              Frame-By-Frame Video Expert
            </p>
          </div>
        </div>
        <div className="flex gap-4">
           {result && (
              <button 
                onClick={handleDownload}
                className="bg-[#007BFF] hover:bg-[#00D1FF] text-white px-8 py-2.5 rounded-full font-bold flex items-center gap-2 transition-all transform hover:scale-105 shadow-lg shadow-[#007BFF]/20"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                Download Strategy
              </button>
           )}
        </div>
      </header>

      <main className="mt-4 space-y-12">
        {/* Hero Section */}
        <section className="max-w-4xl mx-auto">
          {!videoFile ? (
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="pulse-border glass rounded-[2.5rem] p-16 flex flex-col items-center justify-center text-center cursor-pointer hover:bg-white/5 transition-all group duration-500"
            >
              <input 
                type="file" 
                ref={fileInputRef} 
                onChange={handleFileUpload} 
                className="hidden" 
                accept="video/*"
              />
              <div className="mb-6 transform group-hover:scale-110 transition-transform duration-500">
                <UploadIcon />
              </div>
              <h2 className="text-3xl font-extrabold text-white mb-3">Upload Video for Analysis</h2>
              <p className="text-gray-400 max-w-sm mx-auto leading-relaxed">
                Drag & drop your video to identify viral hooks and generate multi-platform SEO strategies.
              </p>
              <div className="mt-10 flex gap-6 text-[10px] font-black text-[#00D1FF] uppercase tracking-widest opacity-60">
                <span className="bg-white/5 px-3 py-1 rounded-full">MP4</span>
                <span className="bg-white/5 px-3 py-1 rounded-full">MOV</span>
                <span className="bg-white/5 px-3 py-1 rounded-full">WEBM</span>
              </div>
            </div>
          ) : (
            <div className="glass rounded-[2.5rem] p-8 relative overflow-hidden">
              <div className="aspect-video w-full rounded-2xl overflow-hidden bg-black mb-8 shadow-2xl border border-white/5">
                <video src={videoPreview!} controls className="w-full h-full object-contain" />
              </div>
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                <button 
                  onClick={() => { setVideoFile(null); setVideoPreview(null); setResult(null); }}
                  className="w-full sm:w-auto px-10 py-3.5 rounded-full border border-white/10 text-gray-300 font-bold hover:bg-white/5 transition-all"
                >
                  Clear Video
                </button>
                <button 
                  onClick={startAnalysis}
                  disabled={isAnalyzing}
                  className={`w-full sm:w-auto px-16 py-3.5 rounded-full font-black text-lg transition-all shadow-2xl flex items-center justify-center gap-3 ${isAnalyzing ? 'bg-gray-800 text-gray-500 cursor-not-allowed' : 'bg-[#007BFF] hover:bg-[#00D1FF] text-white shadow-[#007BFF]/30'}`}
                >
                  {isAnalyzing ? (
                    <>
                      <div className="w-5 h-5 border-2 border-t-transparent border-white rounded-full animate-spin"></div>
                      Analyzing...
                    </>
                  ) : 'Generate Strategy'}
                </button>
              </div>
            </div>
          )}
        </section>

        {/* Loading Overlay */}
        {isAnalyzing && (
          <div className="flex flex-col items-center justify-center py-16 gap-8 animate-pulse">
            <div className="loader-dots relative w-24 h-6">
              <div className="absolute top-0 w-4 h-4 rounded-full bg-[#007BFF]"></div>
              <div className="absolute top-0 w-4 h-4 rounded-full bg-[#007BFF]"></div>
              <div className="absolute top-0 w-4 h-4 rounded-full bg-[#00D1FF]"></div>
              <div className="absolute top-0 w-4 h-4 rounded-full bg-[#00D1FF]"></div>
            </div>
            <div className="text-center">
              <p className="text-2xl font-black text-white tracking-tight">Scanning Frames & Audio...</p>
              <p className="text-sm text-[#00D1FF] font-medium mt-2">Extracting High-CTR elements using Gemini 1.5 Pro</p>
            </div>
          </div>
        )}

        {error && (
          <div className="bg-red-500/10 border border-red-500/30 text-red-500 p-5 rounded-2xl text-center max-w-xl mx-auto font-medium">
            {error}
          </div>
        )}

        {/* Results Section */}
        {result && !isAnalyzing && (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-1000">
            {/* Hook & Policy Summary */}
            <div className="grid lg:grid-cols-5 gap-6">
              <div className="lg:col-span-3 glass p-8 rounded-3xl border-l-[6px] border-l-[#00D1FF] shadow-xl">
                <h4 className="text-[#00D1FF] font-black text-xs uppercase tracking-[0.2em] mb-3">AI Detected Visual Hook</h4>
                <p className="text-2xl text-white font-bold leading-tight tracking-tight">"{result.visualHook}"</p>
              </div>
              <div className={`lg:col-span-2 glass p-8 rounded-3xl border-l-[6px] shadow-xl ${result.policyCheck.status === 'Safe' ? 'border-l-green-500' : 'border-l-orange-500'}`}>
                <div className="flex justify-between items-center mb-3">
                  <h4 className="text-gray-400 font-black text-xs uppercase tracking-[0.2em]">Policy Compliance</h4>
                  <span className={`text-[10px] px-3 py-1 rounded-full font-black uppercase tracking-wider ${result.policyCheck.status === 'Safe' ? 'bg-green-500/20 text-green-500' : 'bg-orange-500/20 text-orange-500'}`}>
                    {result.policyCheck.status}
                  </span>
                </div>
                <p className="text-sm text-gray-300 font-medium leading-relaxed">{result.policyCheck.notes}</p>
              </div>
            </div>

            {/* Platform Specific Strategies */}
            <div className="grid lg:grid-cols-3 gap-8">
              <SEOCard 
                platform="YouTube" 
                icon={<YTIcon />} 
                content={[
                  { label: 'Viral CTR Title', value: result.youtube.title },
                  { label: 'Keywords Description', value: result.youtube.description },
                  { label: 'High-Volume Tags', value: result.youtube.tags }
                ]}
              />
              <SEOCard 
                platform="TikTok" 
                icon={<TikTokIcon />} 
                content={[
                  { label: 'Catchy Captions', value: result.tiktok.captions },
                  { label: 'Trending Hashtags', value: result.tiktok.hashtags.map(h => h.startsWith('#') ? h : `#${h}`).join(' ') }
                ]}
              />
              <SEOCard 
                platform="Facebook" 
                icon={<FBIcon />} 
                content={[
                  { label: 'Engagement Caption', value: result.facebook.caption }
                ]}
              />
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="mt-24 py-12 border-t border-white/5 text-center">
        <div className="flex justify-center items-center gap-2 mb-4 grayscale opacity-50">
          <img src="logo.png" alt="logo" className="w-6 h-6 rounded-full" />
          <span className="font-black text-white tracking-tighter">VidSEO AI</span>
        </div>
        <p className="text-gray-500 text-xs font-medium tracking-wide">© 2024 VidSEO AI. Professional Video Optimization Tool.</p>
        <div className="flex justify-center gap-6 mt-6">
          <a href="#" className="text-[10px] text-gray-600 font-bold hover:text-[#00D1FF] transition-colors">PRIVACY POLICY</a>
          <a href="#" className="text-[10px] text-gray-600 font-bold hover:text-[#00D1FF] transition-colors">TERMS OF SERVICE</a>
          <a href="#" className="text-[10px] text-gray-600 font-bold hover:text-[#00D1FF] transition-colors">API STATUS</a>
        </div>
      </footer>
    </div>
  );
};

export default App;
